openapi: 3.0.0
info:
  title: Tasks API
  version: 1.0.0
servers:
  - url: http://localhost:3000/tasks
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasks'
    post:
      summary: Add a new task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tasks'
      responses:
        '201':
          description: Item created
  /tasks/{id}:
    get:
      summary: Get an task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
    put:
      summary: Update an task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tasks'
      responses:
        '200':
          description: Task updated
    delete:
      summary: Delete a Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted
components:
  schemas:
    Tasks:
      type: object
      properties:
        id:
          type: number
        taskName:
          type: string
        taskDescription:
          type: string
        completed: 
          type: boolean
